steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/beaming-botany-436322-f7/bank-loan-model-train', '.']


- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/beaming-botany-436322-f7/bank-loan-model-train']



# options:
#   logging: CLOUD_LOGGING_ONLY
#   logs_bucket: 'gs://logs-bucket-bank-model'

- name: 'gcr.io/beaming-botany-436322-f7/bank-loan-model-train'
  entrypoint: 'bash'
  args:
   - '-c'
   - |
      python -m pytest
# options:
#   logging: NONE


# - name: 'gcr.io/cloud-builders/git'
#   args: ['clone', 'https://github.com/mrigankomi/Bank_loan_modelling_CICD.git']
      


      

